export enum FindMovieActions {
    SET_MOVIE = "SET_MOVIE",
    CLEAR_MOVIE = "CLEAR_MOVIE",
    SET_MOVIE_MORE = "SET_MOVIE_MORE",
    SET_SEARCH_BODY = "SET_SEARCH_BODY"
}

export enum AuthActions {
    SET_LOGIN_STATUS = "SET_LOGIN_STATUS",
    SET_USER_DATA = "SET_USER_DATA",
    CLEAR_USER_DATA = "CLEAR_USER_DATA",
    SET_SHOW_LOGIN_MODAL = "SET_SHOW_LOGIN_MODAL"
}

export enum WatchLaterActions {
    SET_MOVIE_WATCH_LATER = "SET_MOVIE_WATCH_LATER",
    SET_MOVIE_LATER_MORE = "SET_MOVIE_LATER_MORE"
}