export const API_URL = "http://127.0.0.1:8000/"
export const tokenKey = "token"
export const loginPatch = "/login"
export const refreshTokenPatch = "api/token/refresh/"
export const findmoviePatch = "/findmovie"
export const registrationPatch = "/registration"